# Generated by Django 5.2.5 on 2025-09-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='pruduct',
            new_name='product',
        ),
    ]
