# Generated by Django 5.2.5 on 2025-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_discountcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='percent',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
