# Generated by Django 5.2.5 on 2025-09-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_percent_discountcode_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
